### ISSUE TITLE
uv根本导不出来，那几个label都没用吗？

### ISSUE THREAD

**Issue by listenerl** [Alunice/TaTa#1]

**Comment by Alunice** [comment]
你可以看一下操作视频是如何操作的。先得打开csv文件，人工判断一下uv是在csv的那个label下面，再打开工具选择对应的label。如果csv数据本身就做了uv混淆啥的那就没法正常导uv，你得自己先整理一下csv数据格式

**Comment by listenerl** [comment]
是要自己把csv的label改成与unity一摸一样的语义吗？

**Comment by listenerl** [comment]
是要自己把csv的label改成要导入工具中对应的语义吗

**Comment by Alunice** [comment]
> 是要自己把csv的label改成要导入工具中对应的语义吗

不用。你看csv那个label对应的是uv，然后在工具的uv0页签中选择csv的label就好了。如果还有问题最好能附带你的操作过程截图，以及csv数据格式截图。

**Comment by listenerl** [comment]
![image](https://user-images.githubusercontent.com/69412318/141092242-3b51e441-0f05-41d2-926d-fa8a8fbf1e92.png)
这是csv的数据。
![image](https://user-images.githubusercontent.com/69412318/141092495-14f23d2c-0b51-462d-a4bf-893f581676d7.png)
这是dao导出的操作。
![image](https://user-images.githubusercontent.com/69412318/141092654-2b462dd7-d562-401b-97a2-576692b6d52e.png)
在unity里输出第三套纹理坐标就没有。。。

**Comment by Alunice** [comment]
你可以试一下把textcoord3放到uv0的label标签下去。然后在DCC软件中看一下UV0。以及你如果选择的是UV3X label，对应的其实是第四套纹理坐标。。。。

**Comment by listenerl** [comment]
![image](https://user-images.githubusercontent.com/69412318/141101548-e6917198-f69d-41cb-b834-6913f2040575.png)
这是导出来了？可是我unity里取出来是这样。。。
![image](https://user-images.githubusercontent.com/69412318/141101815-1ba7fbbb-529b-4a9f-80bc-53d6e0385b18.png)

**Comment by listenerl** [comment]
老哥，好像只能放uv0，放uv1，2，3，3dsmax和blender看都没有

**Comment by listenerl** [comment]
放uv0，三维纹理坐标就只能取xy。。。

**Comment by Alunice** [comment]
兄弟，这个我做的时候就是简单自用的，工程源码也放在上面了~你可以看看源码自己改一下。我记得好像我就存了xy两个值，所以三维纹理坐标会有问题吧。太久了我也记不太清了~

**Comment by listenerl** [comment]
好吧
