### ISSUE TITLE
切线和副法线还有计划加吗

### ISSUE THREAD

**Issue by zhzehong** [Alunice/TaTa#2]
CSVConverter/CSVConverter/FbxManager.cs
切线和副法线还有计划加吗

**Comment by qiushuisuoyue** [comment]
同问， @zhzehong 有没有其它的方案？

**Comment by Alunice** [comment]
额。。。源码都放出来了你们看着自己加下吧0.0

**Comment by qiushuisuoyue** [comment]
你好，楼主 我这边尝试将顶点颜色的部分 拷贝过来重新 填写tangent ,但是图片中的字符串我不明白有什么作用，我现在这样修改 虽然程序可以正常运行 但是 还请解释这个字符串应该如何填写？？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alunice/TaTa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月23日(星期三) 下午3:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alunice/TaTa] 切线和副法线还有计划加吗 (Issue #2)





 
额。。。源码都放出来了你们看着自己加下吧0.0

**Comment by qiushuisuoyue** [comment]
@Alunice  帅哥看一下 邮件，不清楚  这里面的字符串 我修改时 能随便改吗？ 具体该如何修改，要参考啥？

**Comment by Alunice** [comment]
> @Alunice 帅哥看一下 邮件，不清楚 这里面的字符串 我修改时 能随便改吗？ 具体该如何修改，要参考啥？

obj格式好像不支持tangent吧，fbx文件你去找一个带tangent的明文打开看看，有格式要求的。包括tangent的起始表记字符串等。

如果你会unity的话，用官方的fbx export导出一个带tagent的模型，选择ascii编码，这样用文本编辑器打开就可以看到fbx的明文格式了。dcc有些软件也是支持导出ascii编码的fbx文件。

**Comment by qiushuisuoyue** [comment]
好的 感谢楼主

**Comment by qiushuisuoyue** [comment]
多谢楼主 ，已经修改了，正不正确 就得试一下了，我使用的fbx,




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alunice/TaTa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月23日(星期三) 下午4:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alunice/TaTa] 切线和副法线还有计划加吗 (Issue #2)





  
@Alunice 帅哥看一下 邮件，不清楚 这里面的字符串 我修改时 能随便改吗？ 具体该如何修改，要参考啥？
  
obj格式好像不支持tangent吧，fbx文件你去找一个带tangent的明文打开看看，有格式要求的。包括tangent的起始表记字符串等。
 
如果你会unity的话，用官方的fbx export导出一个带tagent的模型，选择ascii编码，这样用文本编辑器打开就可以看到fbx的明文格式了。dcc有些软件也是支持导出ascii编码的fbx文件。
